stages:
  - test
  - scan
  - docs
  - build

test:test:dev:
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  image: node:latest
  tags:
    - docker
  stage: test
  only:
    - merge_requests
    - dev
    - main
  script:
    - npm install
    - npm run test-converage
  artifacts:
    paths:
      - coverage
    when: always
    reports:
      junit:
        - junit.xml
      cobertura: coverage/cobertura-coverage.xml


sec:scan:dev:
  image: registry.gitlab.com/gitlab-org/security-products/analyzers/eslint
  tags:
    - docker
  stage: scan
  only:
    - merge_requests
    - dev
    - main
  script:
    - /analyzer run
  artifacts:
    when: always
    reports:
      sast: gl-sast-report.json

make:build:dev:
  image: node:latest
  tags:
    - docker
  stage: build
  only:
    - merge_requests
    - dev
    - main
  script:
    - npm install
    - npm run buildprep
